### ISSUE TITLE
blog: Add tag metadata for blog posts that appear under the post's title

### ISSUE THREAD

**Issue by tacurran** [ory/web#1]
The idea for the blog is to have regular articles published by members of the ory team. The blog should be more focussed on personal insights into product, technical tips about the ory stack, and programming guidelines. Every team member should be able to make contributions.

Allow fo three to five words that can serve as metadata for the blogpost and surface them under the blogpost's title.

**Comment by vinckr** [comment]
We have now
`seo:
keywords: |`
