### ISSUE TITLE
algolia search broken

### ISSUE THREAD

**Issue by vinckr** [ory/web#102]
**Describe the bug**

The search on [ory.sh/docs](https://www.ory.sh/docs/) is not working. 
```

Unable to fetch results

You might want to check network connection
```
**To Reproduce**
try search on [ory.sh/docs](https://www.ory.sh/docs/) 

**Additional context**

Possibly related issue: https://github.com/ory/kratos/issues/967

**Comment by aeneasr** [comment]
These two are not related - this bug was fixed
