### ISSUE TITLE
Not possible to return to home from docs

### ISSUE THREAD

**Issue by aeneasr** [ory/web#138]
**Describe the bug**

When browsing the docs, it is not possible to return back to the ory main website

**To Reproduce**

Go to www.ory.sh/docs and try to get home.

**Comment by jfcurran** [comment]
was this feature implemented in earlier versions?

**Comment by vinckr** [comment]
Right now you can go to Ory Kratos -> Home and then you get to ory.sh/kratos 

Maybe substitute the Kratos/Home with a button in the top bar to get to ory.sh?
The home option under Kratos etc. is imo more confusing than useful.

**Comment by jaredpreston** [comment]
Was never like that in previous versions either. However, it would be to consider how we get back to ory.sh main site from docs. The general path of navigation for visitors of the site is landing -> docs -> and then exit. How about we open links that take people off ory.sh in a new tab? Is it possible to have the logo on docs link to ory.sh?

**Comment by aeneasr** [comment]
This was fixed
