### ISSUE TITLE
content: create open source page

### ISSUE THREAD

**Issue by jaredpreston** [ory/web#142]
There should be a main landing page for open source. The content that should be on this page is the same as was on the original ory.sh index page - on that original landing page there was focus on the open source. From there, there were links off to all the open source project pages specifically for e.g. ory.sh/kratos and ory.sh/hydra

**Comment by jfcurran** [comment]
how does this page differ from the current products page and how can we further differentiate it?

**Comment by jaredpreston** [comment]
After discussion with John Curran - this page is not what should be added. We are creating a products oriented structure on the website and will feature open source projects as products and the overall products page will reflect what was intended here. This issue is closed.
