### ISSUE TITLE
Web URL fails to load without prefix "www"

### ISSUE THREAD

**Issue by Benehiko** [ory/web#162]
**Describe the bug**

Loading directly to a page for instance https://ory.sh/hydra/docs will just load forever. Same for the other sub-pages `/kratos/`, `/keto/` etc.
Adding the prefix, however, fixes this e.g. https://www.ory.sh/hydra/docs/
The root directory, however, https://ory.sh/ will successfully redirect to https://www.ory.sh/

**To Reproduce**

1. Go directly in your browser to https://ory.sh/hydra/docs
2. It will load forever, never redirecting to https://www.ory.sh/hydra/docs

**Expected behavior**

A successful redirect which adds the prefix www

**Environment**

- Version: v1.2.3, git sha hash
- Environment: Debian, Docker, ...

**Additional context**

**Comment by aeneasr** [comment]
Netlify hat an aoutage yesterday, it seems to be working again today: https://www.netlifystatus.com
