### ISSUE TITLE
GitHub Stats animated numbers changes container height

### ISSUE THREAD

**Issue by Benehiko** [ory/web#191]
**Describe the bug**

https://user-images.githubusercontent.com/18033717/119150041-5c149400-ba4e-11eb-946b-22f195dee06a.mov

**To Reproduce**

Change to a viewport similar to ipad.
Scroll to stats section on the landing page

**Expected behavior**

Not to change the height of the container

**Environment**

- Environment: Chrome

**Comment by aeneasr** [comment]
No longer the case!
