### ISSUE TITLE
Weird page subtitle

### ISSUE THREAD

**Issue by sagikazarmark** [ory/web#20]
I recently linked your site on Slack and the rendered subtitle is quite weird:

<img width="380" alt="Screenshot 2020-07-24 at 13 46 21" src="https://user-images.githubusercontent.com/1226384/88388066-10ed0e80-cdb4-11ea-8c40-c319cd176c97.png">

I guess it's not on purpose, so I thought I'd give you a heads up about it.

**Comment by zepatrik** [comment]
Thanks :wink:

**Comment by aeneasr** [comment]
Thank you! This is an upstream issue partially tracked here: https://github.com/facebook/docusaurus/issues/2724

**Comment by aeneasr** [comment]
This has been resolved!
