### ISSUE TITLE
Top for blog posts padding is off

### ISSUE THREAD

**Issue by aeneasr** [ory/web#221]
**Describe the bug**

The top padding is off for blog posts and other content pages (like TOS)

<img width="1392" alt="Bildschirmfoto 2021-06-04 um 10 52 03" src="https://user-images.githubusercontent.com/3372410/120774793-ea931600-c522-11eb-9741-1da14eb1690b.png">

<img width="1392" alt="Bildschirmfoto 2021-06-04 um 10 51 52" src="https://user-images.githubusercontent.com/3372410/120774805-ed8e0680-c522-11eb-96ff-19dae719b695.png">

**To Reproduce**

https://60b9d3086a8ff9e4c0629ebb--wonderful-sinoussi-8532a7.netlify.app/looking-at-keto/

**Expected behavior**

Navigation should count towards top padding of content container

**Comment by Benehiko** [comment]
I believe this has already been fixed in #219 
![image](https://user-images.githubusercontent.com/18033717/120808397-54261b00-c549-11eb-92c8-38c7deafa82a.png)

**Comment by aeneasr** [comment]
I stand corrected, was looking at the wrong preview!
