### ISSUE TITLE
fix: modify out of date About Us description

### ISSUE THREAD

**Issue by tacurran** [ory/web#230]
**Describe the bug**

The current About Us text does not accurately reflect Ory's origin and commitment to open source.

**To Reproduce**

**Expected behavior**

In the navigation, the terminology should be consistent: About Us vs About Ory

**Environment**

- macOS Big Sur 11.4
- Vivaldi 4.0.2312

**Additional context**

The About Us text does not accurately describe Ory's purpose

**Comment by vinckr** [comment]
Implemented in https://github.com/ory/web/pull/293
