### ISSUE TITLE
Codebox used on open-source pages is not sizing correctly and overflows

### ISSUE THREAD

**Issue by jfcurran** [ory/web#244]
**Describe the bug**
Codebox used on open-source pages is not sizing correctly and overflows. Its width also changes in some cases, and the scrollbar that appears on some browsers does not look correct 

**Additional context**
from keto
![Screenshot 2021-06-22 at 18 36 50](https://user-images.githubusercontent.com/24988314/122965758-dce5e900-d388-11eb-8de4-a821ccfac389.png)
![Screenshot 2021-06-22 at 18 36 46](https://user-images.githubusercontent.com/24988314/122965765-de171600-d388-11eb-89fb-53e193c52a24.png)
![Screenshot 2021-06-22 at 18 36 41](https://user-images.githubusercontent.com/24988314/122965767-deafac80-d388-11eb-955d-be3225151d97.png)

from hydra
![Screenshot 2021-06-22 at 18 38 05](https://user-images.githubusercontent.com/24988314/122965903-03a41f80-d389-11eb-89e1-b69c5ac16c1a.png)

**Expected behavior**

Codebox retains it maximum width regardless of content and only changes in height, with sideways scrolling enabled.

**Comment by vinckr** [comment]
this is fixed now @jfcurran ?
