### ISSUE TITLE
theming for open-source pages not implemented

### ISSUE THREAD

**Issue by jfcurran** [ory/web#245]
**Describe the bug**
var(--colors-primary-default) is as color for most highlighted elements on the website, without making use of respective open source product themes (keto, hydra, etc)

**Expected behavior**
Open-source pages should make use of the available themes (keto, hydra, etc) to overwrite the var(--colors-primary-default) color variable. 

**Additional Context**
This can be done in one line by adding the respective theme of open source products to their page inside the layout.tsx component present on all pages.

**Comment by vinckr** [comment]
This is implemented right @jfcurran
