### ISSUE TITLE
Implement representative about us page

### ISSUE THREAD

**Issue by aeneasr** [ory/web#246]
**Is your feature request related to a problem? Please describe.**

The about us page does not represent the people who work here. Let's add all the team members. If you do not have pictures of team members yet please ask them or use a placeholder for now.

**Comment by vinckr** [comment]
This is planned for early July, we can look to bump it up a bit. 
We should update this in concert with https://github.com/ory/web/issues/230. 
If you already have any ideas what to say there let me know, I think the current text is pretty dry ;-)

**Comment by aeneasr** [comment]
Ah missed that this is a dupe. Yes it would be great to update this page!

**Comment by jfcurran** [comment]
Although related, these two issues are no duplicates of each other - I am reopening this so we don't lose track. The one issue is regarding the text content, this one about who works at Ory.

**Comment by jfcurran** [comment]
#293
