### ISSUE TITLE
Flash of unstyled content on page load in safari

### ISSUE THREAD

**Issue by jfcurran** [ory/web#247]
**Describe the bug**
Icons, for example the one inside our CTA, are displayed as dark on page load before the color gets passed to it on safari.

**To Reproduce**
load the page in safari with a clean cache and see what happens to the icons.
_Note: this is not reproducible in development for me, only in deployment._

<img width="1680" alt="Screenshot 2021-06-23 at 10 11 25" src="https://user-images.githubusercontent.com/24988314/123060924-7229c180-d40b-11eb-8922-f1360d218279.png">

**Expected behavior**
Icons are displayed correctly on load

**Environment**
Safari `Version 14.1.1 (16611.2.7.1.4)`

**Additional context**
Flash of unstyled content ([wikipedia](https://en.wikipedia.org/wiki/Flash_of_unstyled_content))

**Comment by vinckr** [comment]
Cant reproduce on `Safari Version 13.1.3 (15609.4.1)`

**Comment by aeneasr** [comment]
The problem is, I believe, that some CSS rules are loaded after the rest of the site. I can see that a class is missing when the network is slow on the image. Once the class is loaded, it applies some filters (like invert) which makes the icons white.

**Comment by aeneasr** [comment]
The flashing happens in other browsers as well

**Comment by aeneasr** [comment]
Ok the problem appears to be related to `useEffect` in `ColourWrapper`
