### ISSUE TITLE
refactor navigation for better browser compatibility

### ISSUE THREAD

**Issue by jfcurran** [ory/web#262]
**Describe the bug**
The navigation is currently not behaving as intended across the most common browsers (safari in particular, chrome, firefox). 
- [x] Nav items that have a dropdown do not show the dropdown on click (safari 13)
- [ ] Items within dropdowns have unwanted behaviour on mouseenter and hover (safari)
  - [x] #220
  - [ ] partially related is the flash of unstyled content on load for some browsers (safari 14) #247 
- [ ] Scroll behaviour within the navigation for mobile devices is unclear #222 

**To Reproduce**
See the respective issues for instructions to reproduce. 

> Nav items that have a dropdown do not show the dropdown on click (safari 13)
open any site in safari 13 and attempt to click on navitems with a dropdown. it wont work

https://user-images.githubusercontent.com/24988314/123655437-435a8380-d82f-11eb-8503-3b7fdd9e32b6.mov

**Expected behavior**
I expect the navigation to function properly, across common browsers, regardless of how it looks. the website navigation is currently causing bad user experience.

**Comment by aeneasr** [comment]
How did you install Safari 13 on your system?

**Comment by jfcurran** [comment]
I didn't - this is from an older machine that has not been updated yet

**Comment by aeneasr** [comment]
Ok I would need that machine to be able to fix the issues :)

**Comment by jfcurran** [comment]
perfect thank you - this is @vinckr's machine 👀

**Comment by vinckr** [comment]
Safari 13 bug:

- https://stackoverflow.com/questions/3047337/does-overflowhidden-applied-to-body-work-on-iphone-safari

**Comment by vinckr** [comment]
It works now without problems on all of my browsers (Safari 13/14, FF, Chrome, Opera, Brave, Vivaldi).
Can this be closed @jfcurran ?

**Comment by jfcurran** [comment]
no :/ scroll behaviour and the flash of unstyled content are still unresolved. 
flash of unstyled content will be resolved once we tackle #268 - the navigation scroll behaviour itself is unclear and needs to be tackled separately

**Comment by aeneasr** [comment]
Since those are tracked as individual issues it probably makes sense to close this?

**Comment by jfcurran** [comment]
okay, that makes sense - then im closing
