### ISSUE TITLE
bug: soft-404 error on community.ory.sh

### ISSUE THREAD

**Issue by vinckr** [ory/web#290]
**Describe the bug**

soft-404 fehler at
https://community.ory.sh/t/config-file-not-found/1209

`Loading failed for the <script> with source “https://sqa-web.ory.sh/np.js”. 1209:1:1`

**To Reproduce**

Visit 
https://community.ory.sh/t/config-file-not-found/1209

**Additional context**

I am guessing only @aeneasr has access to the old community forum (https://community.ory.sh) to disable/remove the script? 
Let me know if there is any way I can fix this.

**Comment by aeneasr** [comment]
Thank you - it's a bit of trouble to enable the discourse forum again to fix this. The correct URL would be `https://sqa-web.ory.sh/js/np.js`.

I don't think it's a big issue for SEO so we can keep this open and if someone has the time to fix it we can address it :)

**Comment by aeneasr** [comment]
Now the webserver is completely down ._.

**Comment by aeneasr** [comment]
Resolved both
