### ISSUE TITLE
refactor footer

### ISSUE THREAD

**Issue by jfcurran** [ory/web#306]
the footer does not yet make use of new functionalities added in #305 
complexity in both .jsx and .css should be reduced and its content seperated from the design found in `layout.tsx`

**Comment by vinckr** [comment]
This is also resolved, right @jfcurran ?

**Comment by jfcurran** [comment]
not quite - coming up this week 💪

**Comment by luharuka** [comment]
is this added if added I would love to work on this @jfcurran please assign it to me
