### ISSUE TITLE
Navigation menu has a gap

### ISSUE THREAD

**Issue by aeneasr** [ory/web#309]
**Describe the bug**

<img width="1325" alt="Bildschirmfoto 2021-07-23 um 16 43 10" src="https://user-images.githubusercontent.com/3372410/126798944-b9cb4a9e-721b-4e8c-b236-9822367857a5.png">

**Comment by jfcurran** [comment]
related to #271

**Comment by aeneasr** [comment]
Yeah but please fix this before refactoring the whole navigation in a small PR. It's probably just one line of code that needs to be changed. It's a pretty serious visual bug.
