### ISSUE TITLE
The Banner breaks the Nav

### ISSUE THREAD

**Issue by Benehiko** [ory/web#339]
**Describe the bug**

When clicking on the banner and then navigate back using the browser back button it will break the nav.
The nav will stay broken until the local storage of the browser is cleared.

https://user-images.githubusercontent.com/18033717/129531638-1debc07e-1a11-485d-a48c-4b1552b877b6.mov

**To Reproduce**

1. Go to https://ory.sh
2. Click on the banner
3. Click on the browser back button
4. If nothing has happened yet, click forward button.
5. This should break the nav until you clear the local storage.

**Expected behavior**

Not break the nav by going back.

**Environment**

- Browser: Firefox, Chrome
- Environment: Linux (Ubuntu 20.04)

**Additional context**

This is consistently reproducible.

**Comment by aeneasr** [comment]
I also see it in chrome and can reproduce it

<img width="2672" alt="Bildschirmfoto 2021-08-16 um 10 11 46" src="https://user-images.githubusercontent.com/3372410/129532413-2521ffaf-af26-4ffa-b36f-d84d2c81be06.png">

Hard/reloading it does not help.

@jfcurran pretty sure this has to do with your banner thingy

**Comment by jfcurran** [comment]
on it, thank you
