### ISSUE TITLE
FEATURE. Remove/refactor Collaborator page

### ISSUE THREAD

**Issue by tacurran** [ory/web#350]
He collaborator page should be merged together with the Team page. Also some collaborations are time bound so we don't want to present this as a consulting page. 

**What is the reasoning behind your suggestions**
The number and type of collaborators changed frequently. It's not material to the audience. 

**Additional context**

Add any other context about the content changes.

**Is your request related to known issues?**

Please add any issues that are related to the content you want to alter.

**Comment by vinckr** [comment]
Closing this for now as this has been updated on https://www.ory.sh/about.
