### ISSUE TITLE
De-duplicate jobs texts

### ISSUE THREAD

**Issue by zepatrik** [ory/web#357]
Some parts are copied between jobs pages, see #355 and #356 for examples. There should only be one place where stuff needs to be fixed.

**Comment by vinckr** [comment]
Those are different job openings. 
They share some common text in the beginning (Intro) and (What’s it like to work at Ory?) . 
We could duplicate this over all openings, but it is not a huge improvement (we updated this twice in the last year).
Wdyt @jfcurran ?

**Comment by zepatrik** [comment]
My point was just that you should not have duplicate text around the pages, as you have to fix typos and stuff everywhere manually, which is not only tedious but also error prone.
If there are sections that are shared across multiple offerings, please extract them to a single place and then import them.

**Comment by jfcurran** [comment]
We can set up shared text passages no problem - considering the scope and usage of these text I don't currently see this as priority. However, we will definitely consider this once we update the jobs page (and pages) real soon

**Comment by zepatrik** [comment]
I can guarantee you that they will be out of sync very soon. But OK, I can also do that real quick
