### ISSUE TITLE
feat: add a section to the website for News Updates

### ISSUE THREAD

**Issue by marneysof** [ory/web#371]
**Is your feature request related to a problem? Please describe.**

I just created a "blog" post about Ory Hydra user Imgur's recent acquisition with overline: Industry News. We put it there because we don't currently have a section for "News Updates" or "Industry News," another area where we could feature an update like this one or, say, articles we publish for external publications… 

**Describe the solution you'd like**

We could create a new section under "Developers" or "Company" Called "Industry News." 

**Describe alternatives you've considered**

Or, we could just keep it in the blog section. 

**Additional context**

**Comment by BlueAcidFrog** [comment]
Great idea Marney, to add: 

It would be great to create a live news feed for Industry news and flag important insights from everywhere, e.g. including news sites, blogs, Twitter, and newsletters. 

Feedly seems to be a good tool for that (https://feedly.com/) 

It allows you to pull content from socials such as Reddit (maybe Hackernews as well) and integrate them directly into a visible feed onsite - Influencers can be integrated as well. 

- Organize all your trusted sources (pick the ones we like and trust) in one place 
- Sharing Industry News, tweets, etc. with the community and team as well (Slack etc.) 

Let's have a closer look at this.
