### ISSUE TITLE
Replace "sign up" -> "try free" or "start building"

### ISSUE THREAD

**Issue by aeneasr** [ory/web#423]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/web/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/web/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Current CTAs match ory closed beta. We are now open and free, and need to update CTAs and language.

### Describe your ideal solution

All buttons leading to the console sign up should now read "Start building" or "try free" instead of "sign up".

<img width="768" alt="Screenshot 2021-11-11 at 13 47 49" src="https://user-images.githubusercontent.com/3372410/141300610-5375b5d7-3306-4c5a-a449-a260865b915e.png">

The secondary button should link to the docs, or alternatively something similar to https://vercel.com/contact/sales

### Workarounds or alternatives

-

### Version

master

**Comment by vinckr** [comment]
done in https://github.com/ory/web/pull/434
