### ISSUE TITLE
add ory/dockertest stars to the webpage statistics

### ISSUE THREAD

**Issue by Bin-fluence** [ory/web#45]
**Is your feature request related to a problem? Please describe.**

Ory is showing up in some VC analysis as a high growth OSS company. But the whole story has yet to be told. For instance we should add dockertest, which is also a popular project for deployment

**Describe the solution you'd like**

add something like https://gist.github.com/yyx990803/7745157
or https://developer.github.com/v3/activity/starring/

**Describe alternatives you've considered**

DOing nothing is not an alternative @aeneasr 

**Additional context**

<img width="861" alt="Screenshot 2020-10-22 at 18 37 37" src="https://user-images.githubusercontent.com/67282336/96903110-b4be8700-1495-11eb-9829-073055ba410f.png">

**Comment by aeneasr** [comment]
I think a product page for Dockertest would be great! Our website already scrapes the most recent star data from GitHub by the way - Dockertest is included as far as I can recall

**Comment by jfcurran** [comment]
@aeneasr I am going to tackle this this week. I'll link the corresponding PR here, after creating a page for dockertest and adding its stats to our stats component on the website :)

**Comment by aeneasr** [comment]
@jfcurran are you still working on this?

**Comment by vinckr** [comment]
Have put it on the roadmap early '22 😄

**Comment by vinckr** [comment]
as mentioned, this is tracked internally (#385), closing as duplicate.
