### ISSUE TITLE
Load Tag Manager before consent hooks

### ISSUE THREAD

**Issue by MicLeey** [ory/web#461]
Currently consent is given and then Google Tag Manager is loaded.

Instead, Google Tag Manager should initialize on page load and modified through the fine-grained consent options introduced in https://github.com/ory/web/pull/428

It can collect minimal analytics before consent options are interacted with so we're currently missing out on those.
https://support.google.com/tagmanager/answer/10718549

**Comment by aeneasr** [comment]
@BlueAcidFrog I believe this would be illegal according to GDPR. IIRC we must not load any google code before having consent. Please check!

**Comment by BlueAcidFrog** [comment]
i will need to look into it and make some research first. Will update you asap.
