### ISSUE TITLE
Blog: add reading time

### ISSUE THREAD

**Issue by zepatrik** [ory/web#50]
It would be nice to have a reading time on top of the page with all the metadata.

**Comment by jfcurran** [comment]
We're adding author avatars, author info, and reading time to the metadata soon :)

**Comment by aeneasr** [comment]
https://www.gatsbyjs.com/plugins/gatsby-remark-reading-time/ could probably help!

**Comment by vinckr** [comment]
@jfcurran As I am working on the /web roadmap and going through open issues, 
do you still want to add this?

**Comment by jfcurran** [comment]
yes
