### ISSUE TITLE
Enhance privacy banner

### ISSUE THREAD

**Issue by jaredpreston** [ory/web#76]
**Is your feature request related to a problem? Please describe.**

The privacy banner that appears when I navigate to ory.sh for the first time or after cookies are flushed needs to be adjusted to make it more clear.

**Describe the solution you'd like**

We need to make it understandable what "necessary means" and what we mean by "statistics". It would be better to call the choices necessary and extended and just provide small definitions of what these mean.  

- necessary would be so that the website functions correctly and certain aspects of it become usable  

- extended would be the collection of extended information via our website analytics program to be able to understand more about who is accessing our website to be able to offer service improvements and enhancements.  

Both these things can of course be read up on in more detail in our privacy policy, which is already referenced.

**Comment by aeneasr** [comment]
I think this can be closed as we no longer use cookies or any other type of PII in analytics any more. We also no longer use Google Analytics!

I can give more insights into how this works if you want to when you are in Munich

**Comment by aeneasr** [comment]
Given that we don't have a banner any more I am going to close this. We could still use a banner to enable cookie tracking but don't have to riht now.
